### ISSUE TITLE
backend 認証の検討のためのコンテナ作成

### ISSUE THREAD

**Issue by Tsucchi-04** [trisets/backend-sandbox#1]

**Comment by Tsucchi-04** [comment]
keycloak というossがあるので、それを動かし検証するために、コンテナを立てる

**Comment by terra-d** [comment]
docker composeでローカルに立ち上げるのをゴールにやりましょう！

**Comment by Tsucchi-04** [comment]
ローカルにコンテナを立ち上げることができたので、クローズします。
Docker Compose経由で立ち上げることを次の目標に
残作業を新規isuueとして作成します。
